services:
  frontend-tester:
    container_name: gigaview_frontend_tester
    build: .
    restart: always
    ports:
      - 5005:5000
    volumes:
      - ./:/app
    command: "python -m gunicorn --reload -w 1 -b 0.0.0.0:5000 app:app"
networks: 
  default: 
    external: 
      name: external-gigaview-network
